# Generated by Django 5.2.7 on 2025-11-06 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('club', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('POR', 'Portero'), ('LD', 'Lateral Derecho'), ('DFC', 'Defensa Central'), ('LI', 'Lateral Izquierdo'), ('MCD', 'Medio Centro Defensivo'), ('MC', 'Medio Centro'), ('MCO', 'Medio Centro Ofensivo'), ('MI', 'Medio Izquierdo'), ('MD', 'Medio Derecho'), ('SD', 'Segundo Delantero'), ('EI', 'Extremo Izquierdo'), ('ED', 'Extremo Derecho'), ('DC', 'Delantero Centro')])),
                ('pace', models.IntegerField()),
                ('shooting', models.IntegerField()),
                ('passing', models.IntegerField()),
                ('dribbling', models.IntegerField()),
                ('defending', models.IntegerField()),
                ('physical', models.IntegerField()),
                ('diving', models.IntegerField()),
                ('reflexes', models.IntegerField()),
                ('handling', models.IntegerField()),
                ('positioning', models.IntegerField()),
                ('kicking', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('overall_rating', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cards', models.ManyToManyField(blank=True, related_name='teams', to='api.card')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.team')),
            ],
        ),
    ]
