# Generated by Django 5.2.7 on 2025-11-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='team_mean',
            field=models.FloatField(default=0),
        ),
    ]
