# Generated by Django 5.2.7 on 2025-11-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='position',
            field=models.CharField(choices=[('POR', 'Portero'), ('LD', 'Lateral Derecho'), ('DFC', 'Defensa Central'), ('LI', 'Lateral Izquierdo'), ('MCD', 'Medio Centro Defensivo'), ('MC', 'Medio Centro'), ('MCO', 'Medio Centro Ofensivo'), ('MI', 'Medio Izquierdo'), ('MD', 'Medio Derecho'), ('SD', 'Segundo Delantero'), ('EI', 'Extremo Izquierdo'), ('ED', 'Extremo Derecho'), ('DC', 'Delantero Centro')]),
        ),
    ]
