# Generated by Django 5.2.8 on 2025-11-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='media',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
